<script type="text/javascript">
$(function() {// jquery buttons
	$( "input:submit", "#button" ).button();
});
</script>
<?php echo $this->headTitle($this->title);?>
<h2><?php echo $this->translate('header-register');?></h2>
<div id="error">
<?php if (isset($this->error)):
		foreach ($this->error as $k => $v):
			echo "$v";
		endforeach;
	endif
?>
</div>
<div id="button">
	<?php echo $this->form ?>
</div>