<?php echo $this->headTitle($this->title);?>
<h2>A propos de VOICES</h2>
<p>
Nous envisageons un monde où toutes les personnes ont les capacités d'améliorer leurs
conditions grâce au Web: un Web unique et ouvert. Tout le monde - indépendamment de sa
langue, sa capacité, son lieu de résidence, son sexe, son âge ou son revenu - sera en
mesure de communiquer et de collaborer, de créer du contenu, et d'accéder aux informations
dont il a besoin pour améliorer sa vie et celle de sa collectivité. Ainsi, la créativité
de milliards de nouveaux utilisateurs sur le Web sera mise à contribution. Les possibilités
du Web vont se décupler, et joueront un rôle de plus en plus vital dans la réduction de la
pauvreté et des conflits, dans l'amélioration de la santé et de l'éducation, dans la
propagation de la bonne gouvernance et permettront de relever les grands défis locaux et
mondiaux.
</p>
<p>
Les agriculteurs et les communautés rurales dans le Sahel ont deux principales sources
d'information: la téléphonie mobile et la radio communautaire. W4RA a l'objectif
d'intégrer la radio communautaire locale et les services Web, d'une façon interactive,
basés sur les technologies voix et le téléphone mobile. La philosophie de W4RA est de
développer des logiciels libre de droit, s'appuyant sur des licenses ouvertes. De cette
façon, on peut s'assurer que les développeurs locaux en Afrique seront en mesure
d'utiliser, ou réutiliser et d'adapter ces logiciels aux besoins locaux. Cela permettra
également à de nouvelles communautés de développeurs de sites Web africains de créer leurs
propres entreprises et de fournir des services innovants basés sur la voix à des
utilisateurs locaux.
</p>
