<?php echo $this->headTitle($this->title);?>
<h2>About Us</h2>
<p>We envision a world where all people are empowered by the Web: One Open Web. Everyone,
regardless of language, ability, location, gender, age or income will be able to communicate
and collaborate, create valued content, and access the information that they need to improve their
lives and communities. Thus, the creativity of billions of new Web users will be unleashed. The
Web's capabilities will multiply, and play an increasingly vital role in reducing poverty and conflict, improving healthcare and education, spreading good governance, addressing big challenges, local and global. W4RA: Web alliance for Regreening in Africa.
Farmers and rural communities in the Sahel have two main sources of information: mobile telephony
and community radio.
</p>
<p>
W4RA integrates local community radio into open and interactive voice-based
mobile Web services. The philosophy of W4RA is to develop Open Source software only. That is the
best way to ensure that local web developers in Africa will be able to use, reuse and adapt the
software to local needs. This will enable new communities of African web developers to start their
own businesses and provide innovative voice-based services to local users.
</p>

