<?php echo $this->headTitle($this->title);?>
<h2>Bienvenue</h2>
<p>
Le World Wide Web a été créé pour tout le monde. Cependant, plus de 4,5 milliard de personnes
n'ont pas accès au Web. L'alliance Web pour le Reverdissement en Afrique (W4RA) est une
initiative pour étendre les avantages du Web et de l'économie de la Connaissance á ceux qui
vivent dans les communautés rurales en Afrique. Pour améliorer l'accès au World Wide Web aux
communautés rurales plusieurs obstacles sont á surmonter. Les défis se trouvent surtout dans
les domaines du contenu, de l'accès et des langues locales. Il est clair que les informations
existante aujourd'hui sur le Web n'est pas totalement pertinente pour les agriculteurs au Sahel.
</p>
<p>
Pourtant, la téléphonie mobile est désormais á la portée de nombreuses personnes dans les zônes
rurales défavorisées. Cette tendance ouvre de nouvelles possibilités. Il faut remarquer que la
plupart des agriculteurs africains ne possèdent pas de portables modernes avec accès á Internet,
mais simplement des téléphones mobiles de première génération, seulement pour parler. La plupart
de gens ne s'en servent même pas pour envoyer ou recevoir des SMS. Le projet W4RA se concentrera
donc sur l'accès et l'interaction avec le Web, basé sur la voix.
</p>
