<?php echo $this->headTitle($this->title);?>
<h2>Welcome</h2>
<p>The World Wide Web is for all of us. But not yet everyone on this planet enjoys its important
benefits: still more than 4.5 billion people do not have access to the Web. The Web alliance for
Regreening in Africa (W4RA) is an initiative to help extend the Web benefits of the knowledge
society and economy to people in rural communities in Africa.
</p>
<p>
To do so serious challenges must be addressed, in content, access, and language. At present
information on the Web is not relevant for farmers in the Sahel. But, mobile telephony is now
in the reach of many poor people. This trend opens up great opportunities. Most African farmers
do not have fancy smart phones with internet access. They use simple old fashioned mobile phones,
only for chatting. They don't even use their phones for sending or receiving SMS. W4RA will
therefore focus on access and interaction with the Web, based on voice.
</p>