<?php echo $this->headTitle($this->title);?>

<div id="message-container">
	<div id="container" class="ui-widget-content ui-corner-all">
		<h3 class="ui-widget-header ui-corner-all">
			<?php echo $this->translate('header-sys-maintenance');?>
		</h3>
			<img src="<?php echo $this->baseUrl(). "/images/sys-down.png";?>">
		<div id="container-msg">
			<?php echo $this->translate('system-maintenance');?>
		</div>
	</div>
</div>