<?php echo $this->headTitle($this->translate('title-com-store'))?>
<script type="text/javascript">
	// buttons
	$(function() {
		$( "a,button", ".button" ).button();
	});
	// tabs
	$(function() {
		$( "#tabs" ).tabs();
	});
</script>

<!-- tabs container  -->
<div id="tabs">
	<ul>
		<li><a href="#tabs-1" class="one"><?php echo $this->translate('label-tab-online');?></a></li>
		<li class="ui-tabs-selected"><a href="#tabs-2" class="two"><?php echo $this->translate('label-tab-com')?></a></li>
<!--  	<li><a href="#tabs-3" class="three">Aenean lacinia</a></li>  -->
	</ul>
	
	<!-- first tab content -->
	<div id="tabs-1">
		<?php if (count($this->comOnline) && isset($this->comOnline)):?>
     	<table class="button">
     		<tr>
     			<th><?php echo $this->translate('table-status');?></th>
     			
     			<th colspan="8"><?php echo $this->translate('table-communique');?>
     		</tr>
     		
     		<tr>
     			<td><?php echo $this->translate('table-pub-online');?></td>
     			
 				<?php foreach ($this->comOnline as $key=>$value):?>
     			<td>
     				<span id="listen-audio">
     					<a href="<?php echo $this->escape($value['content']);?>" target="_blank">
     						<?php echo $this->translate('ORTM Fr');?>
     					</a>
     				</span>
     				
     				<?php $bamUrl = str_replace("_1_fr", "_1_bam", $this->escape($value['content']));?>
  				<span id="listen-audio">
  					<a href="<?php echo $bamUrl; ?>" target="_blank">
  						<?php echo $this->translate('ORTM Bamb');?>
  					</a>
  				</span>
  				
  				<?php $ortmBomuUrl = str_replace("_1_fr", "_1_bomu", $this->escape($value['content']));?>
  				<span id="listen-audio">
  					<a href="<?php echo $ortmBomuUrl; ?>" target="_blank">
  						<?php echo $this->translate('ORTM Bomu');?>
  					</a>
  				</span>
  				
  				<?php
  					$moutianFr = str_replace("_1_", "_2_", $this->escape($value['content']));
  				?>
  				<span id="listen-audio">
  					<a href="<?php echo $moutianFr; ?>" target="_blank">
  						<?php echo $this->translate('Moutian Fr');?>
  					</a>
  				</span>
  				
  				<?php
  					$moutianBam = str_replace("_1_fr", "_2_bam", $this->escape($value['content']));
  				?>
  				<span id="listen-audio">
  					<a href="<?php echo $moutianBam; ?>" target="_blank">
  						<?php echo $this->translate('Moutian Bamb');?>
  					</a>
  				</span>
  				
  				<?php
  					$moutianBomu = str_replace("_1_fr", "_2_bomu", $this->escape($value['content']));
  				?>
  				<span id="listen-audio">
  					<a href="<?php echo $moutianBomu; ?>" target="_blank">
  						<?php echo $this->translate('Moutian Bomu');?>
  					</a>
  				</span>

     			</td>
     			<?php endforeach;?>
      		    <td>
     				<a href="<?php echo $this->url(array(
            								'module'=>'market',
			    							'controller'=>'market-info',
			    							'action'=>'print',
			    							'com-id'=>$this->escape($value['com_id'])),
			    							'default', true
            								);?>">
  			  		<?php echo $this->translate('preview');?>
  			 		</a>
     			</td>

     			<td>
     				<a href="<?php echo $this->url(array(
           										'module'=>'market',
           									  	'controller'=>'ngo',
           										'action'=>'show-communique-content',
           										'id'=>$this->escape($value['upload_id'])),
           										'default', true
           									  );?>">
						<?php echo $this->translate('label-com-content');?>
					</a>
				</td>
     		</tr>
     		
		</table>
		
		<?php elseif(isset($this->sysOffline)):?>
			<?php echo $this->translate('system-offline');?>
		<?php else:?>
			<?php echo $this->translate('no-com-online');?>
		<?php endif;?>
	</div>
	
	<!-- second tab content -->
	<div id="tabs-2">
	<!-- previous communique available -->
	<?php if (count($this->paginator)): ?>
	
	<!-- pagination -->
	<?php echo $this->paginator;?>
	
	<table class="button">
  	<tr>
  	 	<th colspan="1">&nbsp;</th>
<!--  	<th><?php echo $this->translate('table-language');?></th>   -->
    	<th>Com No.</th>
    	<th><?php echo $this->translate('table-status');?></th>
    	<th><?php echo $this->translate('table-date-delivered');?></th>
<!--   	<th><?php echo $this->translate('table-radio-station');?></th>   -->
    	<th colspan="3"><?php echo $this->translate('table-communique');?></th>
  	</tr>
  	<?php $counter = 1;?>
  	<?php foreach ($this->paginator as $key => $value):?>
  	<tr id="<?php if (($counter % 2) == 0): echo 'even'; else: echo 'odd'; endif;?>">
 <!--   <td><input type="hidden" name="upload_id" value="<?php echo $this->escape($value['upload_id']); ?>"/></td>  -->
    	<td><?php echo $counter++;?></td>
<!--  	<td><?php
  				if ($this->escape($value['lang_code'] == 'fr'))
  					echo $this->translate('lang-french');
  			?>
  		</td>
-->
  		<td align="center"><?php echo $this->escape($value['com_number']);?></td>
  		<td><?php echo $this->translate('table-status-pub')?></td>
  		<td>
  			<?php echo $this->escape(date('D, M j Y', strtotime($value['ts_date_delivered'])));?>
  		</td>
<!--
  		<td><span id="radio-sta-text-up">Radio ORTM Segou</span>
  			<span id="listen-audio">Radio Moutian</span>
  		</td>
-->
  		<td>
  			<span id="listen-audio">
  			<a href="<?php echo $this->escape($value['content']);?>" target="_blank">
  				<?php echo $this->translate('ORTM French');?>
  			</a>
  			</span>

  			<?php $bamUrl = str_replace("_1_fr", "_1_bam", $this->escape($value['content']));?>
  			<span id="listen-audio">
  				<a href="<?php echo $bamUrl; ?>" target="_blank">
  					<?php echo $this->translate('ORTM Bamb');?>
  				</a>
  			</span>
  				
  			<?php $ortmBomuUrl = str_replace("_1_fr", "_1_bomu", $this->escape($value['content']));?>
  			<span id="listen-audio">
  				<a href="<?php echo $ortmBomuUrl; ?>" target="_blank">
  					<?php echo $this->translate('ORTM Bomu');?>
  				</a>
  			</span>
  			<?php
  				$moutianFr = str_replace("_1_", "_2_", $this->escape($value['content']));
  			?>
  			<span id="listen-audio">
  			<a href="<?php echo $moutianFr; ?>" target="_blank">
  				<?php echo $this->translate('Moutian Fr');?>
  			</a>
  			</span>
  			
  			<?php
  				$moutianBam = str_replace("_1_fr", "_2_bam", $this->escape($value['content']));
  			?>
  			<span id="listen-audio">
  				<a href="<?php echo $moutianBam; ?>" target="_blank">
  					<?php echo $this->translate('Moutian Bamb');?>
  				</a>
  			</span>
  				
  			<?php
  				$moutianBomu = str_replace("_1_fr", "_2_bomu", $this->escape($value['content']));
  			?>
  			<span id="listen-audio">
  				<a href="<?php echo $moutianBomu; ?>" target="_blank">
  					<?php echo $this->translate('Moutian Bomu');?>
  				</a>
  			</span>
  		</td>
  		
  		<td><a href="<?php echo $this->url(array(
            								'module'=>'market',
			    							'controller'=>'market-info',
			    							'action'=>'print',
			    							'com-id'=>$this->escape($value['com_id'])),
			    							'default', true
            								);?>">
  			  <?php echo $this->translate('preview');?>
  			 </a>
  		</td>
  		<td>
  			<a href="<?php echo $this->url(array(
           										'module'=>'market',
           									  	'controller'=>'ngo',
           										'action'=>'show-communique-content',
           										'id'=>$this->escape($value['upload_id'])),
           										'default', true
           									  );?>">
				<?php echo $this->translate('label-com-content');?>
			</a>
		</td>
  	</tr>
  	<?php endforeach;?>
	</table>
	
	<?php else:?>
          <?php echo $this->translate('empty-com-store');?>
	<?php endif;?>
	</div>
<!--
	<div id="tabs-3">
		<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
		<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
	</div>
 -->
</div>
