<?php echo $this->headTitle($this->translate('title-search'));?>

<script type="text/javascript">
	$(function() {
		$( "input:submit", "#button" ).button();
	});
</script>

<h2><?php echo $this->translate('header-search');?></h2>

<div id="button">
	<?php echo $this->form;?>
</div>

<h2><?php echo $this->translate('header-search-results');?></h2>
<p><?php echo count($this->results) .' '. $this->translate('results-found');?></p>

<?php if (count($this->results)):?>
	<?php $x=1;?>
	<?php foreach ($this->results as $r): ?>
  		
		<?php $x++;?>
	<?php endforeach;?>
<?php endif;?>