<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
		<title><?php echo $this->title;?></title>
		<?php echo $this->headMeta();?>
		<?php echo $this->headLink()->appendStylesheet($this->baseUrl(). '/css/admin.css');?>
		<?php echo $this->jQuery();?>
	</head>
	
	<script type="text/javascript">
		$(function() {
			$("a#menu-button", "#menu").button();
		});
	</script>

	<body>
	<div id="header">
		<div id="logo">
			<img src=<?php echo $this->baseUrl(). "/images/logo.png";?> /></img>
		</div>
		<div id="menu">
			<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
				<a id="menu-button" href="<?php echo $this->url(array(
																	  'controller' => 'admin',
																      'action' => 'home'), 'default', true); ?>">HOME</a>
				
				<a id="menu-button" href="<?php echo $this->url(array(), 'logout'); ?>">LOGOUT</a>
			<?php endif; ?>
		</div>
	</div>
	
	<!-- output flash message -->
	<?php echo $this->partial('priorityMessages.phtml',
				   				array('priorityMessages'=>$this->priorityMessenger()));
	?>
	
	<div id="content">
		<?php echo $this->layout()->content ?>
	</div>
	
	<div id="footer">
		<?php echo $this->translate('copyright');?>&nbsp;
		<a href="http://www.mvoices.eu" target="_blank">EU VOICES Project</a>&nbsp;&copy;
		<?php echo date('Y');?>
	</div>
	</body>
</html>